# Generated by Django 3.2.13 on 2022-06-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0002_auto_20220608_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelime',
            name='image',
            field=models.ImageField(default='kelimeler/default.jpg', upload_to='kelimeler/%Y/%m/%d/'),
        ),
    ]
